# Generated by Django 4.0 on 2021-12-13 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocPortalApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File_Type',
            new_name='File_Types',
        ),
        migrations.RenameModel(
            old_name='User_Doc',
            new_name='User_Docs',
        ),
    ]
